apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-emp-java
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-emp-java
    spec:
      containers:
      - name: azure-emp-java
        image: vkacr.azurecr.io/empapp
        ports:
        - containerPort: 8080
               
---
apiVersion: v1
kind: Service
metadata:
  name: azure-emp-java
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: azure-emp-java